export const arrayOf = {
    WEAPON_PROPERTIES: 'DATA_ARRAYOF_WEAPON_PROPERTIES'
};

export const bool = {
    BOOL: 'DATA_BOOL_STANDARD',
    HAS_DISADVANTAGE: 'DATA_BOOL_HAS_DISADVANTAGE',
    YES_NO: 'DATA_BOOL_YES_NO'
};

export const number = {
    COIN: 'DATA_NUMBER_COIN',
    DEC: 'DATA_NUMBER_DECIMAL',
    INT: 'DATA_NUMBER_INTEGER',
    WEIGHT: 'DATA_NUMBER_WEIGHT'
};

export const picklist = {
    ARMOR_PROFICIENCY: 'DATA_PICKLIST_ARMOR_PROFICIENCY',
    DAMAGE_TYPE: 'DATA_PICKLIST_DAMAGE_TYPE',
    WEAPON_CATEGORY: 'DATA_PICKLIST_WEAPON_CATEGORY',
    WEAPON_PROFICIENCY: 'DATA_PICKLIST_WEAPON_PROFICIENCY'
};

export const special = {
    DICE_ROLL: 'DATA_SPECIAL_DICE_ROLL',
    WEAPON_RANGE: 'DATA_SPECIAL_WEAPON_RANGE'
};

export const string = {
    STRING: 'DATA_STRING_STANDARD'
};