export const ARMOR_PROFICIENCY = 84;
export const DAMAGE_TYPES = 81;
export const WEAPON_CATEGORY = 83;
export const WEAPON_PROFICIENCY = 82;

export const MELEE_WEAPON_CATEGORY = 65;
export const RANGED_WEAPON_CATEGORY = 66;
export const SIMPLE_WEAPON_PROFICIENCY = 67;
export const MARTIAL_WEAPON_PROFICIENCY = 68;