export const LOAD_ARMORS_SUCCESS = 'LOAD_ARMORS_SUCCESS';
export const UPDATE_ARMOR_SUCCESS = 'UPDATE_ARMOR_SUCCESS';
export const CREATE_ARMOR_SUCCESS = 'CREATE_ARMOR_SUCCESS';
export const DELETE_ARMOR_SUCCESS = 'DELETE_ARMOR_SUCCESS';
export const UPSERT_ARMOR_SUCCESS = 'UPSERT_ARMOR_SUCCESS';

export const LOAD_BACKGROUNDS_SUCCESS = 'LOAD_BACKGROUNDS_SUCCESS';
export const UPDATE_BACKGROUND_SUCCESS = 'UPDATE_BACKGROUND_SUCCESS';
export const CREATE_BACKGROUND_SUCCESS = 'CREATE_BACKGROUND_SUCCESS';
export const DELETE_BACKGROUND_SUCCESS = 'DELETE_BACKGROUND_SUCCESS';
export const UPSERT_BACKGROUND_SUCCESS = 'UPSERT_BACKGROUND_SUCCESS';

export const LOAD_DIEROLLS_SUCCESS = 'LOAD_DIEROLLS_SUCCESS';
export const CREATE_DIEROLL_SUCCESS = 'CREATE_DIEROLL_SUCCESS';

export const LOAD_EQUIPMENTS_SUCCESS = 'LOAD_EQUIPMENTS_SUCCESS';
export const UPDATE_EQUIPMENT_SUCCESS = 'UPDATE_EQUIPMENT_SUCCESS';
export const CREATE_EQUIPMENT_SUCCESS = 'CREATE_EQUIPMENT_SUCCESS';
export const DELETE_EQUIPMENT_SUCCESS = 'DELETE_EQUIPMENT_SUCCESS';
export const UPSERT_EQUIPMENT_SUCCESS = 'UPSERT_EQUIPMENT_SUCCESS';

export const LOAD_ITEMTYPES_SUCCESS = 'LOAD_ITEMTYPES_SUCCESS';
export const UPDATE_ITEMTYPE_SUCCESS = 'UPDATE_ITEMTYPE_SUCCESS';
export const CREATE_ITEMTYPE_SUCCESS = 'CREATE_ITEMTYPE_SUCCESS';
export const DELETE_ITEMTYPE_SUCCESS = 'DELETE_ITEMTYPE_SUCCESS';
export const UPSERT_ITEMTYPE_SUCCESS = 'UPSERT_ITEMTYPE_SUCCESS';

export const LOAD_PACKS_SUCCESS = 'LOAD_PACKS_SUCCESS';
export const UPDATE_PACK_SUCCESS = 'UPDATE_PACK_SUCCESS';
export const CREATE_PACK_SUCCESS = 'CREATE_PACK_SUCCESS';
export const DELETE_PACK_SUCCESS = 'DELETE_PACK_SUCCESS';
export const UPSERT_PACK_SUCCESS = 'UPSERT_PACK_SUCCESS';

export const LOAD_PICKLISTS_SUCCESS = 'LOAD_PICKLISTS_SUCCESS';
export const ADD_PICKLISTITEM_SUCCESS = 'ADD_PICKLISTITEM_SUCCESS';
export const REMOVE_PICKLISTITEM_SUCCESS = 'REMOVE_PICKLISTITEM_SUCCESS';

export const LOAD_PROFICIENCIES_SUCCESS = 'LOAD_PROFICIENCIES_SUCCESS';
export const UPDATE_PROFICIENCY_SUCCESS = 'UPDATE_PROFICIENCY_SUCCESS';
export const CREATE_PROFICIENCY_SUCCESS = 'CREATE_PROFICIENCY_SUCCESS';
export const DELETE_PROFICIENCY_SUCCESS = 'DELETE_PROFICIENCY_SUCCESS';
export const UPSERT_PROFICIENCY_SUCCESS = 'UPSERT_PROFICIENCY_SUCCESS';

export const LOAD_WEAPONS_SUCCESS = 'LOAD_WEAPONS_SUCCESS';
export const UPDATE_WEAPON_SUCCESS = 'UPDATE_WEAPON_SUCCESS';
export const CREATE_WEAPON_SUCCESS = 'CREATE_WEAPON_SUCCESS';
export const DELETE_WEAPON_SUCCESS = 'DELETE_WEAPON_SUCCESS';
export const UPSERT_WEAPON_SUCCESS = 'UPSERT_WEAPON_SUCCESS';

export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_OUT = 'LOG_OUT';