export const LOAD_ITEMTYPES_SUCCESS = 'LOAD_ITEMTYPES_SUCCESS';
export const UPDATE_ITEMTYPE_SUCCESS = 'UPDATE_ITEMTYPE_SUCCESS';
export const CREATE_ITEMTYPE_SUCCESS = 'CREATE_ITEMTYPE_SUCCESS';
export const DELETE_ITEMTYPE_SUCCESS = 'DELETE_ITEMTYPE_SUCCESS';
export const UPSERT_ITEMTYPE_SUCCESS = 'UPSERT_ITEMTYPE_SUCCESS';

export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_OUT = 'LOG_OUT';