export const LOAD_DIEROLLS_SUCCESS = 'LOAD_DIEROLLS_SUCCESS';
export const CREATE_DIEROLL_SUCCESS = 'CREATE_DIEROLL_SUCCESS';

export const LOAD_ITEMTYPES_SUCCESS = 'LOAD_ITEMTYPES_SUCCESS';
export const UPDATE_ITEMTYPE_SUCCESS = 'UPDATE_ITEMTYPE_SUCCESS';
export const CREATE_ITEMTYPE_SUCCESS = 'CREATE_ITEMTYPE_SUCCESS';
export const DELETE_ITEMTYPE_SUCCESS = 'DELETE_ITEMTYPE_SUCCESS';
export const UPSERT_ITEMTYPE_SUCCESS = 'UPSERT_ITEMTYPE_SUCCESS';

export const LOAD_PICKLISTS_SUCCESS = 'LOAD_PICKLISTS_SUCCESS';
export const ADD_PICKLISTITEM_SUCCESS = 'ADD_PICKLISTITEM_SUCCESS';
export const REMOVE_PICKLISTITEM_SUCCESS = 'REMOVE_PICKLISTITEM_SUCCESS';

export const LOAD_WEAPONS_SUCCESS = 'LOAD_WEAPONS_SUCCESS';
export const UPDATE_WEAPON_SUCCESS = 'UPDATE_WEAPON_SUCCESS';
export const CREATE_WEAPON_SUCCESS = 'CREATE_WEAPON_SUCCESS';
export const DELETE_WEAPON_SUCCESS = 'DELETE_WEAPON_SUCCESS';
export const UPSERT_WEAPON_SUCCESS = 'UPSERT_WEAPON_SUCCESS';

export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_OUT = 'LOG_OUT';